#!/usr/bin/env bash

set -eux

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "$here"
  for file in $(find . -name 'Vagrantfile' -type f);
  do
    pushd $(dirname $file)
      # Provide a clean slate
      vagrant destroy -f

      # Install NixOS
      vagrant up --provision || true

      # Force reboot
      vagrant reload

      # Verify the success
      uname=$(printf "uname -a\nexit\n" | vagrant ssh | tail -n1)
      if ! grep "NixOS" <<< $uname >/dev/null;
      then
        echo "Expected NixOS, found: $uname"
        exit 1
      fi
    popd
  done
popd
