#!/bin/bash

set -e

## TODO: Input validation

function check_existence
{
  printf "Checking for $1... "
  which $1 > /dev/null 2>&1
  exists=$?
  if [ "$exists" -eq "0" ];
  then
    echo "found" 1>&2
  else
    echo "not found; see the README" 1>&2
    exit 1
  fi
}
check_existence "pcregrep"
check_existence "unsquashfs"

iso=latest-iso-minimal-x86_64-linux
if [ ! -d host/nix/store ];
then
  mkdir -p mnt host/nix
  wget http://nixos.org/releases/nixos/$iso
  modprobe loop
  mount -o loop $iso mnt
  unsquashfs -d host/nix/store mnt/nix-store.squashfs '*'
fi

## Save one space
rm -f latest-iso-minimal-x86_64-linux

./stage1
