#!/bin/sh

set -e

## TODO: Input validation

## TODO: Don't assume we're debian-based
apt-get install -y squashfs-tools pcregrep

iso=latest-iso-minimal-x86_64-linux
if [ ! -e host/nixos/store ];
then
  mkdir -p mnt host/nix
  wget http://nixos.org/releases/nixos/$iso
  modprobe loop
  mount -o loop $iso mnt
  unsquashfs -d host/nix/store mnt/nix-store.squashfs '*'
fi

## Save one space
rm -f latest-iso-minimal-x86_64-linux

./stage1
