#!/bin/sh

set -e

cp /etc/{external-,}resolv.conf
nixos-generate-config --root /nixos

cat <<EOF > /nixos/etc/nixos/configuration-additions.nix
  boot.kernelParams = ["boot.shell_on_fail"];
  boot.loader.grub.device = "/dev/sda";
  boot.loader.grub.storePath = "/nixos/nix/store";
  boot.initrd.postDeviceCommands = ''
    mkdir -p /mnt-root/old-root ;
    mount -t ext4 /dev/sda1 /mnt-root/old-root ;
  '';
  fileSystems = {
    "/" = {
      device = "/old-root/nixos";
      fsType = "none";
      "options" = "bind";
    };
    "/old-root" = {
      device = "/dev/sda1";
      fsType = "ext4";
    };
  };
}
EOF

nixos_dir=/nixos/etc/nixos
mv $nixos_dir/{,backup-}configuration.nix
head --lines=-1 $nixos_dir/backup-configuration.nix > $nixos_dir/configuration.nix
cat $nixos_dir/configuration-additions.nix >> $nixos_dir/configuration.nix

mv $nixos_dir/{,backup-}hardware-configuration.nix
pcregrep -Mv "fileSystems.\"/\"[\s\S]*};" $nixos_dir/backup-hardware-configuration.nix > $nixos_dir/hardware-configuration.nix

nixos-install --root /nixos
exit
