#!/bin/sh

set -x
set -e

#apt-get install -y squashfs-tools

# TODO: If not already done
#mkdir -p mnt host/nix
#wget http://nixos.org/releases/nixos/latest-iso-minimal-x86_64-linux
#modprobe loop
#mount -o loop latest-iso-minimal-x86_64-linux mnt
#unsquashfs -d host/nix/store mnt/nix-store.squashfs '*'

# TODO: Just for dev
rm -f latest-iso-minimal-x86_64-linux

## For network

cd host
mkdir -p etc dev proc sys
cp /etc/resolv.conf etc/external-resolv.conf
for fn in dev proc sys; do mount --bind /$fn $fn; done

## Patch the ISO for local chroot
INIT=$(find . -type f -path '*nixos*/init')
echo "INIT=$INIT"
BASH=$(find . -type f -path '*/bin/bash' | tail -n 1)
echo "BASH=$BASH"

## Don't run systemd on chroot start, run bash
sed -i "s,exec systemd,exec /$BASH -i /_drafts/stage2," $INIT

## Don't try to remount / since we didn't do a proper phase 1
sed -i "s|mount -n -o remount,rw none /|echo 'not remounting /'|" $INIT

mkdir -p /nixos nixos
mount --bind /nixos nixos

mkdir -p _drafts
mount --bind /_drafts _drafts

chroot . /$INIT
