#!/bin/sh

set -eu

here=$1

## Enable networking
cd host
mkdir -p etc dev proc sys
cp /etc/resolv.conf etc/external-resolv.conf
for fn in dev proc sys; do mount --bind /$fn $fn; done

## Patch the ISO for local chroot
INIT=$(find . -type f -path '*nixos*/init')
echo "INIT=$INIT"
BASH=$(find . -type f -path '*/bin/bash' | tail -n 1)
echo "BASH=$BASH"

## Don't run systemd on chroot start, run our stage2 script
sed -i "s,exec systemd,exec /$BASH -i /nix-in-place/stage2," $INIT

## Don't try to remount / since we didn't do a proper phase 1
sed -i "s|mount -n -o remount,rw none /|echo 'not remounting /'|" $INIT

mkdir -p /nixos nixos
mount --bind /nixos nixos

## Allow stage2 to access these scripts
mkdir -p nix-in-place
mount --bind $here nix-in-place

## Imbue the modified live CD environment so we can install
chroot . /$INIT
