#!/bin/sh

set -eu

check_existence()
{
  set +e
  which $1 > /dev/null 2>&1
  exists=$?
  if [ ! "$exists" -eq "0" ];
  then
    log "$1 not found; see the README for dependencies" 1>&2
    exit 1
  fi
  set -e
}

show_help()
{
  log "usage: $0 [OPTION...]"
  log
  log "  -h  Show this help message"
  log "  -g  Set GRUB target device (default: $grub_device)"
  log "  -r  Set root filesystem target device (default: $root_mount)"
  log "  -t  Set root filesystem type (default: $root_type)"
  log "  -G  Use the graphical NixOS ISO (default: $iso)"
  exit 1
}

log()
{ printf ">>> $@\n"; }
log_start()
{ printf ">>> $@"; }
log_end()
{ printf "$@\n"; }
