Vagrant.configure("2") do |config|
  config.vm.box = "fedora/25-cloud-base"

  config.vm.provision "shell", inline: <<-SHELL
    dnf -y install squashfs-tools git wget
  SHELL
  config.vm.provision "file", source: "../../extra-config", destination: "nixos-extra-config"
  config.vm.provision "shell", path: "../../provision"
end
