Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vbguest.no_install = true

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git squashfs-tools
  SHELL
  config.vm.provision "file", source: "../../extra-config", destination: "nixos-extra-config"
  config.vm.provision "shell", path: "../../provision"
end
